export const SKILLS = {
    languagesAndTools: [
        "html",
        "css",
        "javascript",
        "typescript",
        "sass",
        // "cpp",
        // "java",
        // "python",
        "nodejs",
        "webpack",
        "vite",
        "firebase",
        // "moralis",
        // "stripe",
        "figma",
        "tanstack-query",
    ],
    librariesAndFrameworks: [
        "react",
        "redux",
        "nextjs",
        "tailwindcss",
        "styledcomponents",
        "antdesign",
        "chakra-ui",
    ],
    databases: ["mysql", "mongodb"],
    other: ["git", "sanity-io"],
};
